heat_template_version: 2016-10-14

parameters:
  flavor:
    type: string
    description: 16G flavor
    default: ci.m1.xxlarge
    constraints:
      - custom_constraint: nova.flavor
  image:
    type: string
    description: SNO Snapshot
    default: sno-bcqhp-master-0_10.0.131.137_test
    constraints:
      - custom_constraint: glance.image

resources:
  heat_network:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true
      name: sno_network
  heat_network_subnet:
    type: OS::Neutron::Subnet
    properties:
      network: { get_resource: heat_network }
      cidr: "10.0.128.0/17"
      gateway_ip: "10.0.128.1"
      ip_version: 4
  heat_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: public }
      name: heat_router
  heat_router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: heat_router }
      subnet: { get_resource: heat_network_subnet }
  heat_server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: heat_network }
      fixed_ips:
        - subnet_id: { get_resource: heat_network_subnet }
          ip_address: 10.0.131.137
      security_groups:
        - sno-bcqhp-master
  heat_server:
    type: OS::Nova::Server
    properties:
      name: sno-bcqhp-master-0
      flavor: { get_param: flavor }
      image: { get_param: image }
      networks:
        - port: { get_resource: heat_server_port}
  heat_server_public_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: "public"
  heat_server_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: heat_server_public_ip }
      port_id: { get_resource: heat_server_port }

outputs:
  heat_server_public_ip:
    description: IP Address of the deployed heat_server instance
    value: { get_attr: [ heat_server_public_ip, floating_ip_address ]}
